In [159]:
import numpy as np 
import pandas as pd
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import style

In [160]:
df = pd.read_csv("sgemm_product.csv")
#df.head()
df["RunF"]= (df["Run1 (ms)"] + df["Run2 (ms)"]+ df["Run3 (ms)"]+df["Run4 (ms)"])/4
df=df.drop(columns=['Run1 (ms)', 'Run2 (ms)', 'Run3 (ms)', 'Run4 (ms)'])
#df.head()
dfl=df
df['RunF'].mean()
dfl['RunF_binary'] = np.where(df['RunF']>=3.7878695764981335e-15, 1, 0)
#logistic Dataset
df_log=dfl.drop(columns=['RunF'])
#replicate test and train for logistic regression with binary y 
from sklearn.model_selection import train_test_split 
trainl,testl = train_test_split(df_log,test_size = 0.4, random_state=5000)


In [147]:


X_lr = trainl.iloc[:, 0:14]
oneslr = np.ones([X_lr.shape[0],1])
X_lr = np.concatenate((oneslr,X_lr),axis=1)

y_lr =  trainl.iloc[:, -1].values #.values converts it from pandas.core.frame.DataFrame to numpy.ndarray
theta_lr = np.zeros([1,15])

#set hyper parameters
alpha = 0.5
iters = 5

In [170]:

#define sigmoid for predicted y 
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


def predicted_y(X_lr, theta_lr):
    return sigmoid(np.dot(X_lr, theta_lr.T))

#computecost logistic
def computecost_l(h, y_lr):
    return (-y_lr * np.log(h) - (1 - y_lr) * np.log(1 - h)).mean()





In [165]:
computecost_l(0.1,1)

2.3025850929940455

In [156]:
predicted_y()

In [154]:
y_lr=y_lr.reshape([-1,1])

In [174]:
###THETA VALUES AND COSTS ARE NOT UPDATING
def gradientDescent(X_lr,y_lr,theta_lr,iters,alpha):
    cost_l = np.zeros(iters)
    #test_cost = np.zeros(iters)
    for i in range(iters):
        print("Thetas are :",theta_lr)
        
        h = predicted_y(X_lr,theta_lr)
        
        print("Predicted y is ",h)
        #h[i]= sigmoid(z[i])
        #sub = (alpha/len(X_lr)) * np.sum(X_lr * (h - y_lr), axis=0)
        #print("value being subtracted from theta ", sub )
        theta_lr = theta_lr - alpha*(np.dot(X_lr.T, (h - y_lr)) / y_lr.shape[0])
        theta_lr
        cost_l[i] = computecost_l(h, y_lr)
        print("Updated cost is ",cost_l[i])
        
        
        
    
    return theta_lr, cost_l

#running the gd and cost function
g_lr,cost_l = gradientDescent(X_lr,y_lr,theta_lr,iters,alpha)
print(g_lr)

finalCost_l = computecost_l(h,y_lr)
print(finalCost_l)






Thetas are : [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Predicted called 
Predicted y is  [[0.5]
 [0.5]
 [0.5]
 ...
 [0.5]
 [0.5]
 [0.5]]
computer cost called 
Updated cost is  0.6931471805599453
Thetas are : [[ 0.25        0.25        0.25        0.25        0.25        0.25
   0.25        0.25        0.25        0.25        0.25        0.25
   0.25        0.25        0.25      ]
 [20.12326159 20.12326159 20.12326159 20.12326159 20.12326159 20.12326159
  20.12326159 20.12326159 20.12326159 20.12326159 20.12326159 20.12326159
  20.12326159 20.12326159 20.12326159]
 [20.07135762 20.07135762 20.07135762 20.07135762 20.07135762 20.07135762
  20.07135762 20.07135762 20.07135762 20.07135762 20.07135762 20.07135762
  20.07135762 20.07135762 20.07135762]
 [ 6.37825607  6.37825607  6.37825607  6.37825607  6.37825607  6.37825607
   6.37825607  6.37825607  6.37825607  6.37825607  6.37825607  6.37825607
   6.37825607  6.37825607  6.37825607]
 [ 3.48458885  3.48458885  3.48458885  3.48458885

C:\Users\Hashir\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log
  
C:\Users\Hashir\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in multiply
  


Updated cost is  nan
Thetas are : [[ 0.25        0.25        0.25        0.25        0.25        0.25
   0.25        0.25        0.25        0.25        0.25        0.25000001
   0.25000001  0.25000001  0.25000001]
 [20.12326159 20.12326159 20.12326159 20.12326159 20.12326159 20.12326159
  20.12326159 20.12326159 20.12326159 20.12326159 20.12326159 20.12326181
  20.12326181 20.12326181 20.12326181]
 [20.07135762 20.07135762 20.07135762 20.07135762 20.07135762 20.07135762
  20.07135762 20.07135762 20.07135762 20.07135762 20.07135762 20.07135784
  20.07135784 20.07135784 20.07135784]
 [ 6.37825607  6.37825607  6.37825607  6.37825607  6.37825607  6.37825607
   6.37825607  6.37825607  6.37825607  6.37825607  6.37825607  6.37825628
   6.37825628  6.37825628  6.37825629]
 [ 3.48458885  3.48458885  3.48458885  3.48458885  3.48458885  3.48458885
   3.48458885  3.48458885  3.48458885  3.48458885  3.48458885  3.48458896
   3.48458896  3.48458896  3.48458896]
 [ 3.48413355  3.48413355  3.48413355

Predicted y is  [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
computer cost called 
Updated cost is  nan
[[ 0.25        0.25        0.25        0.25        0.25        0.25
   0.25        0.25        0.25        0.25        0.25        0.25000005
   0.25000005  0.25000005  0.25000005]
 [20.12326159 20.12326159 20.12326159 20.12326159 20.12326159 20.12326159
  20.12326159 20.12326159 20.12326159 20.12326159 20.12326159 20.12326249
  20.12326248 20.12326249 20.12326249]
 [20.07135762 20.07135762 20.07135762 20.07135762 20.07135762 20.07135762
  20.07135762 20.07135762 20.07135762 20.07135762 20.07135762 20.07135852
  20.07135851 20.07135852 20.07135852]
 [ 6.37825607  6.37825607  6.37825607  6.37825607  6.37825607  6.37825607
   6.37825607  6.37825607  6.37825607  6.37825607  6.37825607  6.37825693
   6.37825692  6.37825693  6.37825693]
 [ 3.48458885  3.48458885  3.48458885  3.48

In [175]:
finalCost_l

0.6931471805599453

In [176]:
cost_l

array([0.69314718,        nan,        nan,        nan,        nan])

In [178]:
g_lr

array([[ 0.25      ,  0.25      ,  0.25      ,  0.25      ,  0.25      ,
         0.25      ,  0.25      ,  0.25      ,  0.25      ,  0.25      ,
         0.25      ,  0.25000005,  0.25000005,  0.25000005,  0.25000005],
       [20.12326159, 20.12326159, 20.12326159, 20.12326159, 20.12326159,
        20.12326159, 20.12326159, 20.12326159, 20.12326159, 20.12326159,
        20.12326159, 20.12326249, 20.12326248, 20.12326249, 20.12326249],
       [20.07135762, 20.07135762, 20.07135762, 20.07135762, 20.07135762,
        20.07135762, 20.07135762, 20.07135762, 20.07135762, 20.07135762,
        20.07135762, 20.07135852, 20.07135851, 20.07135852, 20.07135852],
       [ 6.37825607,  6.37825607,  6.37825607,  6.37825607,  6.37825607,
         6.37825607,  6.37825607,  6.37825607,  6.37825607,  6.37825607,
         6.37825607,  6.37825693,  6.37825692,  6.37825693,  6.37825693],
       [ 3.48458885,  3.48458885,  3.48458885,  3.48458885,  3.48458885,
         3.48458885,  3.48458885,  3.48458885, 